// Mock employee data for initial load
export const MOCK_EMPLOYEES = [
  {
    id: 'EMP0001',
    fullName: 'Rajesh Kumar',
    gender: 'Male',
    dob: '1990-05-15',
    state: 'Maharashtra',
    isActive: true,
    createdAt: '2024-01-10T10:30:00Z',
  },
  {
    id: 'EMP0002',
    fullName: 'Priya Singh',
    gender: 'Female',
    dob: '1992-08-22',
    state: 'Delhi',
    isActive: true,
    createdAt: '2024-01-12T09:15:00Z',
  },
  {
    id: 'EMP0003',
    fullName: 'Amit Patel',
    gender: 'Male',
    dob: '1988-03-10',
    state: 'Gujarat',
    isActive: false,
    createdAt: '2024-01-08T14:45:00Z',
  },
  {
    id: 'EMP0004',
    fullName: 'Sneha Verma',
    gender: 'Female',
    dob: '1995-11-30',
    state: 'Uttar Pradesh',
    isActive: true,
    createdAt: '2024-01-11T11:20:00Z',
  },
  {
    id: 'EMP0005',
    fullName: 'Vikram Sharma',
    gender: 'Male',
    dob: '1991-07-18',
    state: 'Karnataka',
    isActive: true,
    createdAt: '2024-01-09T08:50:00Z',
  },
  {
    id: 'EMP0006',
    fullName: 'Anjali Desai',
    gender: 'Female',
    dob: '1994-02-25',
    state: 'Maharashtra',
    isActive: false,
    createdAt: '2024-01-07T15:30:00Z',
  },
  {
    id: 'EMP0007',
    fullName: 'Rohan Das',
    gender: 'Male',
    dob: '1989-09-12',
    state: 'West Bengal',
    isActive: true,
    createdAt: '2024-01-06T10:00:00Z',
  },
  {
    id: 'EMP0008',
    fullName: 'Neha Gupta',
    gender: 'Female',
    dob: '1993-12-05',
    state: 'Punjab',
    isActive: true,
    createdAt: '2024-01-05T16:20:00Z',
  },
];

// Indian States
export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
].sort();
